`include "cmos.v"
/* Generated by Yosys 0.7 (git sha1 61f6811, gcc 6.2.0-11ubuntu1 -O2 -fdebug-prefix-map=/build/yosys-OIL3SR/yosys-0.7=. -fstack-protector-strong -fPIC -Os) */

(* top =  1  *)
(* src = "demux_conductual.v:1" *)
module demux_estructural_sintetizado(clk, reset_L, data_out0, data_out1, data_in);
  (* src = "demux_conductual.v:62" *)
  wire _00_;
  (* src = "demux_conductual.v:15" *)
  wire [3:0] _01_;
  (* src = "demux_conductual.v:15" *)
  wire [3:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "demux_conductual.v:2" *)
  input clk;
  (* src = "demux_conductual.v:6" *)
  input [3:0] data_in;
  (* src = "demux_conductual.v:4" *)
  output [3:0] data_out0;
  (* src = "demux_conductual.v:5" *)
  output [3:0] data_out1;
  (* src = "demux_conductual.v:3" *)
  input reset_L;
  (* src = "demux_conductual.v:8" *)
  wire selector;
  (* src = "demux_conductual.v:11" *)
  wire [3:0] y_0;
  (* src = "demux_conductual.v:12" *)
  wire [3:0] y_1;
  NOT _22_ (
    .A(reset_L),
    .Y(_03_)
  );
  NOR _23_ (
    .A(_03_),
    .B(selector),
    .Y(_00_)
  );
  NAND _24_ (
    .A(_00_),
    .B(y_1[2]),
    .Y(_04_)
  );
  NOT _25_ (
    .A(selector),
    .Y(_05_)
  );
  NOR _26_ (
    .A(_03_),
    .B(_05_),
    .Y(_06_)
  );
  NAND _27_ (
    .A(_06_),
    .B(data_in[2]),
    .Y(_07_)
  );
  NAND _28_ (
    .A(_07_),
    .B(_04_),
    .Y(data_out1[2])
  );
  NAND _29_ (
    .A(_00_),
    .B(y_1[3]),
    .Y(_08_)
  );
  NAND _30_ (
    .A(_06_),
    .B(data_in[3]),
    .Y(_09_)
  );
  NAND _31_ (
    .A(_09_),
    .B(_08_),
    .Y(data_out1[3])
  );
  NAND _32_ (
    .A(_00_),
    .B(data_in[0]),
    .Y(_10_)
  );
  NAND _33_ (
    .A(_06_),
    .B(y_0[0]),
    .Y(_11_)
  );
  NAND _34_ (
    .A(_11_),
    .B(_10_),
    .Y(data_out0[0])
  );
  NAND _35_ (
    .A(_00_),
    .B(data_in[1]),
    .Y(_12_)
  );
  NAND _36_ (
    .A(_06_),
    .B(y_0[1]),
    .Y(_13_)
  );
  NAND _37_ (
    .A(_13_),
    .B(_12_),
    .Y(data_out0[1])
  );
  NAND _38_ (
    .A(_00_),
    .B(data_in[2]),
    .Y(_14_)
  );
  NAND _39_ (
    .A(_06_),
    .B(y_0[2]),
    .Y(_15_)
  );
  NAND _40_ (
    .A(_15_),
    .B(_14_),
    .Y(data_out0[2])
  );
  NAND _41_ (
    .A(_00_),
    .B(data_in[3]),
    .Y(_16_)
  );
  NAND _42_ (
    .A(_06_),
    .B(y_0[3]),
    .Y(_17_)
  );
  NAND _43_ (
    .A(_17_),
    .B(_16_),
    .Y(data_out0[3])
  );
  NAND _44_ (
    .A(_00_),
    .B(y_1[0]),
    .Y(_18_)
  );
  NAND _45_ (
    .A(_06_),
    .B(data_in[0]),
    .Y(_19_)
  );
  NAND _46_ (
    .A(_19_),
    .B(_18_),
    .Y(_02_[0])
  );
  NAND _47_ (
    .A(_00_),
    .B(y_1[1]),
    .Y(_20_)
  );
  NAND _48_ (
    .A(_06_),
    .B(data_in[1]),
    .Y(_21_)
  );
  NAND _49_ (
    .A(_21_),
    .B(_20_),
    .Y(_02_[1])
  );
  NAND _50_ (
    .A(_07_),
    .B(_04_),
    .Y(_02_[2])
  );
  NAND _51_ (
    .A(_09_),
    .B(_08_),
    .Y(_02_[3])
  );
  NAND _52_ (
    .A(_11_),
    .B(_10_),
    .Y(_01_[0])
  );
  NAND _53_ (
    .A(_13_),
    .B(_12_),
    .Y(_01_[1])
  );
  NAND _54_ (
    .A(_15_),
    .B(_14_),
    .Y(_01_[2])
  );
  NAND _55_ (
    .A(_17_),
    .B(_16_),
    .Y(_01_[3])
  );
  NAND _56_ (
    .A(_19_),
    .B(_18_),
    .Y(data_out1[0])
  );
  NAND _57_ (
    .A(_21_),
    .B(_20_),
    .Y(data_out1[1])
  );
  DFF _58_ (
    .C(clk),
    .D(_00_),
    .Q(selector)
  );
  DFF _59_ (
    .C(clk),
    .D(_01_[0]),
    .Q(y_0[0])
  );
  DFF _60_ (
    .C(clk),
    .D(_01_[1]),
    .Q(y_0[1])
  );
  DFF _61_ (
    .C(clk),
    .D(_01_[2]),
    .Q(y_0[2])
  );
  DFF _62_ (
    .C(clk),
    .D(_01_[3]),
    .Q(y_0[3])
  );
  DFF _63_ (
    .C(clk),
    .D(_02_[0]),
    .Q(y_1[0])
  );
  DFF _64_ (
    .C(clk),
    .D(_02_[1]),
    .Q(y_1[1])
  );
  DFF _65_ (
    .C(clk),
    .D(_02_[2]),
    .Q(y_1[2])
  );
  DFF _66_ (
    .C(clk),
    .D(_02_[3]),
    .Q(y_1[3])
  );
endmodule
